logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info

spring:
  datasource:
    url: jdbc:postgresql://1.117.59.182:5432/inyaw?currentSchema=public&sslmode=disable
    username: postgres
    password: inyaw2025
    driver-class-name: org.postgresql.Driver

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub