logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:mysql://172.17.32.7:3306/inyaw?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: Yuxh3318375!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
