name: java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装jdk21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: 查看版本信息
        run: |
          java --version
      - name: 校验Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: gradle授权
        run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v3
      - name: 编译
        run: ./gradlew build
      - name: 查看当前文件
        run: ls -R build
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: 编译docker镜像
        with:
          image: inyaa/inyaw
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: ssh部署
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop $(sudo docker ps -a | grep "inyaw" | awk '{print $1}')
            docker rm -f $(sudo docker ps -a | grep inyaw | awk '{print $1}')
            docker rmi $(sudo docker images | grep inyaw | awk '{print $3}')
            docker run -d -p 8080:8080 --name inyaw --network inyaw --network-alias inyaw docker.io/inyaa/inyaw:latest
